### ISSUE TITLE
Hello author

### ISSUE THREAD

**Issue by dsl2kobe** [zhanbao2000/classroom_attendance_face_recognition#2]
After completing the project deployment, we are unable to obtain the 16 digit random administrator password. Where can I find this password? Thank you very much to the author.

**Comment by zhanbao2000** [comment]
When you first deploy this project, the `app.py` will call `init_db()`

https://github.com/zhanbao2000/classroom_attendance_face_recognition/blob/bd111ba73967ef980168598728c4bd3f99e61f60/app.py#L58-L62

In `init_db()`, admin username and password will be created and printed in the console.

https://github.com/zhanbao2000/classroom_attendance_face_recognition/blob/bd111ba73967ef980168598728c4bd3f99e61f60/db.py#L45

https://github.com/zhanbao2000/classroom_attendance_face_recognition/blob/bd111ba73967ef980168598728c4bd3f99e61f60/db.py#L55-L59

**Comment by dsl2kobe** [comment]
Thank you for your reply. But the problem still hasn't been solved. I tried to change default-admiin_password=secrets. token_urlsafe (16) to default-admiin_password=123456789. But it still shows a password error and cannot find the password in the log. I tried to find the password in the database, but it was encrypted with a hash value and could not be obtained. I did everything I could. If possible, could you add a WeChat account to facilitate future problem-solving. If there is any violation, please forgive me

**Comment by dsl2kobe** [comment]
> 感谢您的回复。但问题仍然没有得到解决。我试图更改 default-admiin_password=secrets。token_urlsafe （16） 设置为 default-admiin_password=123456789。但它仍然显示密码错误，并且在日志中找不到密码。我试图在数据库中找到密码，但它是用哈希值加密的，无法获取。我做了我能做的一切。如果可能的话，你能不能添加一个微信账户，以方便将来解决问题。如有违规行为，敬请见谅

my wechat is dsl7223.Hope you can add me
